FROM python:3.12.9-alpine3.21

WORKDIR /app

RUN apk update

COPY ./requirements.txt .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ARG YANDEX_CLIENT_ID_ARG
ARG YANDEX_CLIENT_SECRET_ARG
ARG REDIRECT_YANDEX_ARG
ARG OUR_URL_ARG
ARG JWT_ALGORITHM_ARG
ARG JWT_SECRET_ARG
ARG TOKEN_LIFETIME_ARG

ENV YANDEX_CLIENT_ID=$YANDEX_CLIENT_ID_ARG
ENV YANDEX_CLIENT_SECRET=$YANDEX_CLIENT_SECRET_ARG
ENV REDIRECT_YANDEX=$REDIRECT_YANDEX_ARG
ENV OUR_URL=$OUR_URL_ARG
ENV JWT_ALGORITHM=$JWT_ALGORITHM_ARG
ENV JWT_SECRET=$JWT_SECRET_ARG
ENV TOKEN_LIFETIME=$TOKEN_LIFETIME_ARG

CMD ["python", "run-api.py"]
