services:
  db_api:
    image: drhy6yc/bot_api:0.0.3
    container_name: db_api
    ports:
      - "8000:8000"
    networks:
      - network_bot
    restart: unless-stopped

networks:
  network_bot:
    driver: bridge