services:
  bot:
    build: .
    environment:
      YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID}
      YANDEX_CLIENT_SECRET: ${YANDEX_CLIENT_SECRET}
      REDIRECT_YANDEX: ${REDIRECT_YANDEX}
      OUR_URL: ${OUR_URL}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_SECRET: ${JWT_SECRET}
      TOKEN_LIFETIME: ${TOKEN_LIFETIME}
    ports:
      - "8000:8000"
    networks:
      - network_bot
    restart: unless-stopped

networks:
  network_bot:
    driver: bridge