services:
  db_api:
    image: drhy6yc/bot_api:0.0.1
    container_name: db_api
    ports:
      - "8000:8000"
    networks:
      - network_bot
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - clientID
      - redirect_us_uri

networks:
  network_bot:
    driver: bridge